2022-11-09 00:28:21,537 WARNING:Retrying (Retry(total=9, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /webinterface/Bamboo.ashx?command=fundInfoHead_NEW
2022-11-09 00:29:09,526 WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15c9f57f0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/9edf4fbe845b3cf051afd681e2482a4e/window
2022-11-09 00:29:09,556 WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15e47b128>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/efdac2e5435c85fb25e8a455916e2d84/window
2022-11-09 00:29:09,564 WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15e47b9b0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/c3772efd61d4d7cfde1b096ad95dab43/window
2022-11-09 00:29:09,565 WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15e47bd68>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/a57eadffd072edd5570b8fa9b63d3569/window
2022-11-09 00:29:09,568 WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15e56ad30>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/c3772efd61d4d7cfde1b096ad95dab43/window
2022-11-09 00:29:09,570 WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15e56a390>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/efdac2e5435c85fb25e8a455916e2d84/window
2022-11-09 00:29:09,570 WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15c9ddd30>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/9edf4fbe845b3cf051afd681e2482a4e/window
2022-11-09 00:29:09,571 WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15e56ad68>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/a57eadffd072edd5570b8fa9b63d3569/window
2022-11-09 00:29:09,571 WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15e56a978>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/c3772efd61d4d7cfde1b096ad95dab43/window
2022-11-09 00:29:09,602 WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15e46a160>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/efdac2e5435c85fb25e8a455916e2d84/window
2022-11-09 00:29:09,606 WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15e424ac8>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/a57eadffd072edd5570b8fa9b63d3569/window
2022-11-09 00:29:09,606 WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15e46a048>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/9edf4fbe845b3cf051afd681e2482a4e/window
2022-11-09 00:29:11,468 WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15ca77160>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/4adbac5e5f9a66dd7e9f4c97ee4fb80b/url
2022-11-09 00:29:11,493 WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15e47bcc0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/4adbac5e5f9a66dd7e9f4c97ee4fb80b/url
2022-11-09 00:29:11,523 WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15e45bc50>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/4adbac5e5f9a66dd7e9f4c97ee4fb80b/url
2022-11-09 00:29:11,574 WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15ca94fd0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/4adbac5e5f9a66dd7e9f4c97ee4fb80b/window
2022-11-09 00:29:11,615 WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15e46f898>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/4adbac5e5f9a66dd7e9f4c97ee4fb80b/window
2022-11-09 00:29:11,626 WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11445c0b8>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/4adbac5e5f9a66dd7e9f4c97ee4fb80b/window
2022-11-09 00:44:22,070 WARNING:Retrying (Retry(total=9, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /djapi/fund/002096
2022-11-09 07:15:18,033 WARNING:Retrying (Retry(total=9, connect=2, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1592e12b0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /djapi/fund/010555
2022-11-09 07:15:18,035 WARNING:Retrying (Retry(total=9, connect=4, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x15ad73f98>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /sitedataapi/CryptogramAPI.asmx/GetData?data=2eHwS6xvghs%3D
2022-11-09 07:15:19,307 WARNING:Retrying (Retry(total=8, connect=1, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x15aca4b38>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /djapi/fund/010555
2022-11-09 07:15:19,334 WARNING:Retrying (Retry(total=8, connect=3, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x15acbda20>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /sitedataapi/CryptogramAPI.asmx/GetData?data=2eHwS6xvghs%3D
2022-11-09 07:15:21,395 WARNING:Retrying (Retry(total=7, connect=0, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1592e1780>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /djapi/fund/010555
2022-11-09 07:15:21,395 WARNING:Retrying (Retry(total=7, connect=2, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1592e1080>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /sitedataapi/CryptogramAPI.asmx/GetData?data=2eHwS6xvghs%3D
2022-11-09 07:20:20,567 WARNING:Retrying (Retry(total=9, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response'))': /djapi/fund/010554
2022-11-09 08:09:31,596 WARNING:Retrying (Retry(total=9, connect=5, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response'))': /sitedataapi/CryptogramAPI.asmx/GetData?data=6dBuCc30bdc%3D
2022-11-09 08:11:25,531 WARNING:Retrying (Retry(total=9, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response'))': /djapi/fund/013595
2022-11-09 08:18:57,411 WARNING:Retrying (Retry(total=9, connect=5, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response'))': /sitedataapi/CryptogramAPI.asmx/GetData?data=tOmATFnYWjM%3D
2022-11-09 08:48:20,869 WARNING:Retrying (Retry(total=9, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response'))': /djapi/fund/002561
2022-11-09 08:48:27,155 WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15acef5f8>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3f5ab656c20236cea575c0987fc8eee3/window
2022-11-09 08:48:27,157 WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15ace6d30>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3f5ab656c20236cea575c0987fc8eee3/window
2022-11-09 08:48:27,159 WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15ace6978>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3f5ab656c20236cea575c0987fc8eee3/window
2022-11-09 21:08:39,250 WARNING:Retrying (Retry(total=9, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response'))': /djapi/fund/013357
2022-11-09 21:08:59,569 WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15bc61160>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/23899b106d883fb73061cf0af60beb2a/window
2022-11-09 21:08:59,574 WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15bc61978>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/75786692b791ac7f7d3070a322d73f99/window
2022-11-09 21:08:59,580 WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15baf2e10>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/75786692b791ac7f7d3070a322d73f99/window
2022-11-09 21:08:59,582 WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15bafe198>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/23899b106d883fb73061cf0af60beb2a/window
2022-11-09 21:08:59,586 WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15baf21d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/75786692b791ac7f7d3070a322d73f99/window
2022-11-09 21:08:59,592 WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15baf2eb8>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/23899b106d883fb73061cf0af60beb2a/window
2022-11-09 21:35:00,312 WARNING:Retrying (Retry(total=9, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /djapi/fund/006440
2022-11-09 21:38:49,299 WARNING:Retrying (Retry(total=9, connect=5, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response'))': /sitedataapi/CryptogramAPI.asmx/GetData?data=OtgCHL1S71k%3D
2022-11-09 21:39:37,443 WARNING:Retrying (Retry(total=9, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /webinterface/Bamboo.ashx?command=fundInfoHead_NEW
2022-11-09 21:48:25,412 WARNING:Retrying (Retry(total=9, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /djapi/fund/006536
2022-11-09 21:57:06,514 WARNING:Retrying (Retry(total=9, connect=5, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /sitedataapi/CryptogramAPI.asmx/GetData?data=%2FNc6LAhYm%2Bw%3D
2022-11-09 22:05:22,159 WARNING:Retrying (Retry(total=9, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response'))': /webinterface/Bamboo.ashx?command=fundInfoHead_NEW
2022-11-09 22:13:55,786 WARNING:Retrying (Retry(total=9, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /webinterface/Bamboo.ashx?command=fundInfoHead_NEW
2022-11-09 22:18:57,639 WARNING:Retrying (Retry(total=9, connect=5, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response'))': /sitedataapi/CryptogramAPI.asmx/GetData?data=g26DjlCJLxA%3D
2022-11-09 22:24:01,732 WARNING:Retrying (Retry(total=9, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /djapi/fund/012734
2023-01-20 11:54:51,195 WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x157f3c8d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/61b466a015651c88d79f72772a5be8b4/element
2023-01-20 11:54:51,197 WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x158a44c88>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/61b466a015651c88d79f72772a5be8b4/element
2023-01-20 11:54:51,198 WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x158a44940>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/61b466a015651c88d79f72772a5be8b4/element
2023-01-20 21:36:38,967 WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15239d5c0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/82a5be16cebd36f420d6ac8d4e791410/element
2023-01-20 21:36:38,970 WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15486b470>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/82a5be16cebd36f420d6ac8d4e791410/element
2023-01-20 21:36:38,971 WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15486b080>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/82a5be16cebd36f420d6ac8d4e791410/element
2023-01-20 21:36:39,479 WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15486b668>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/82a5be16cebd36f420d6ac8d4e791410/element
2023-01-20 21:36:39,480 WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15486ba58>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/82a5be16cebd36f420d6ac8d4e791410/element
2023-01-20 21:36:39,481 WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15486bba8>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/82a5be16cebd36f420d6ac8d4e791410/element
2023-01-20 21:36:39,990 WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x154873048>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/82a5be16cebd36f420d6ac8d4e791410/element
2023-01-20 21:36:39,992 WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1548732e8>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/82a5be16cebd36f420d6ac8d4e791410/element
2023-01-20 21:36:39,994 WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x154873438>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/82a5be16cebd36f420d6ac8d4e791410/element
2023-01-20 21:36:40,501 WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1548733c8>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/82a5be16cebd36f420d6ac8d4e791410/element
2023-01-20 21:36:40,502 WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15486bf98>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/82a5be16cebd36f420d6ac8d4e791410/element
2023-01-20 21:36:40,504 WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15486b828>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/82a5be16cebd36f420d6ac8d4e791410/element
2023-01-20 21:36:41,008 WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15486b7b8>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/82a5be16cebd36f420d6ac8d4e791410/element
2023-01-20 21:36:41,009 WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15486b0b8>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/82a5be16cebd36f420d6ac8d4e791410/element
2023-01-20 21:36:41,011 WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15486b588>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/82a5be16cebd36f420d6ac8d4e791410/element
2023-01-20 21:36:41,520 WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15486b198>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/82a5be16cebd36f420d6ac8d4e791410/element
2023-01-20 21:36:41,522 WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x154873b70>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/82a5be16cebd36f420d6ac8d4e791410/element
2023-01-20 21:36:41,523 WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x154873470>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/82a5be16cebd36f420d6ac8d4e791410/element
2023-01-20 21:36:42,029 WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1548734e0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/82a5be16cebd36f420d6ac8d4e791410/element
2023-01-20 21:36:42,031 WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x154873128>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/82a5be16cebd36f420d6ac8d4e791410/element
2023-01-20 21:36:42,032 WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x154873cc0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/82a5be16cebd36f420d6ac8d4e791410/element
2023-01-20 21:36:42,540 WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1548790f0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/82a5be16cebd36f420d6ac8d4e791410/element
2023-01-20 21:36:42,542 WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1548793c8>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/82a5be16cebd36f420d6ac8d4e791410/element
2023-01-20 21:36:42,543 WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x154879518>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/82a5be16cebd36f420d6ac8d4e791410/element
2023-01-20 21:36:43,049 WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15486b0f0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/82a5be16cebd36f420d6ac8d4e791410/element
2023-01-20 21:36:43,051 WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15486b240>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/82a5be16cebd36f420d6ac8d4e791410/element
2023-01-20 21:36:43,052 WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15486b438>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/82a5be16cebd36f420d6ac8d4e791410/element
2023-01-20 21:56:55,304 WARNING:Retrying (Retry(total=9, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response'))': /djapi/fund/017393
2023-01-20 22:43:45,563 WARNING:Retrying (Retry(total=9, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response'))': /webinterface/Bamboo.ashx?command=fundInfoHead_NEW
2023-01-20 22:51:39,286 WARNING:Retrying (Retry(total=9, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response'))': /webinterface/Bamboo.ashx?command=fundInfoHead_NEW
2023-01-20 22:54:43,001 WARNING:Retrying (Retry(total=9, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response'))': /webinterface/Bamboo.ashx?command=fundInfoHead_NEW
2023-01-20 23:40:57,690 WARNING:Retrying (Retry(total=9, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response'))': /webinterface/Bamboo.ashx?command=fundInfoHead_NEW
2023-01-20 23:50:15,262 WARNING:Retrying (Retry(total=9, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response'))': /djapi/fund/519628
2023-01-21 00:07:12,549 WARNING:Retrying (Retry(total=9, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response'))': /djapi/fund/960016
2023-01-21 00:38:58,211 WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x151050438>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2f5dc8f9a180ab35bbc1aabbc39d071c/element
2023-01-21 00:38:58,214 WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x151075978>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2f5dc8f9a180ab35bbc1aabbc39d071c/element
2023-01-21 00:38:58,257 WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x151075278>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2f5dc8f9a180ab35bbc1aabbc39d071c/element
2023-01-21 00:38:58,298 WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1510e45f8>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2f5dc8f9a180ab35bbc1aabbc39d071c/window
2023-01-21 00:38:58,318 WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x151322c18>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2f5dc8f9a180ab35bbc1aabbc39d071c/window
2023-01-21 00:38:58,341 WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x151322cf8>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2f5dc8f9a180ab35bbc1aabbc39d071c/window
2023-01-21 00:38:58,588 WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15105cf28>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/235a6a2e5fe4dae3350842561ccea4df/url
2023-01-21 00:38:58,629 WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x151050470>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/235a6a2e5fe4dae3350842561ccea4df/url
2023-01-21 00:38:58,651 WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x151333588>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/235a6a2e5fe4dae3350842561ccea4df/url
2023-01-21 00:38:58,676 WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1513225c0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/235a6a2e5fe4dae3350842561ccea4df/window
2023-01-21 00:38:58,696 WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x152c22438>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/235a6a2e5fe4dae3350842561ccea4df/window
2023-01-21 00:38:58,719 WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x152c224a8>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/235a6a2e5fe4dae3350842561ccea4df/window
2023-01-21 00:38:58,744 WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1510cd400>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/dc9586e19011b15940eb9dc948984251/url
2023-01-21 00:38:58,753 WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15105c898>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/95ac61b7494bf381ee6f158e09d7a9d3/url
2023-01-21 00:38:58,764 WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x151322940>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/dc9586e19011b15940eb9dc948984251/url
2023-01-21 00:38:58,764 WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x151322978>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/95ac61b7494bf381ee6f158e09d7a9d3/url
2023-01-21 00:38:58,788 WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x152c22860>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/dc9586e19011b15940eb9dc948984251/url
2023-01-21 00:38:58,789 WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x152c229b0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/95ac61b7494bf381ee6f158e09d7a9d3/url
2023-01-21 00:38:58,795 WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x152c22e10>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/dc9586e19011b15940eb9dc948984251/window
2023-01-21 00:38:58,796 WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x152c40128>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/95ac61b7494bf381ee6f158e09d7a9d3/window
2023-01-21 00:38:58,800 WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x152c403c8>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/dc9586e19011b15940eb9dc948984251/window
2023-01-21 00:38:58,804 WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x152c40588>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/95ac61b7494bf381ee6f158e09d7a9d3/window
2023-01-21 00:38:58,805 WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x152c40518>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/dc9586e19011b15940eb9dc948984251/window
2023-01-21 00:38:58,813 WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x152c22828>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/95ac61b7494bf381ee6f158e09d7a9d3/window
2023-01-21 00:39:00,626 WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15105c748>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b2409af2052e8ddd9327582a22d15bb6/url
2023-01-21 00:39:00,680 WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x152c40a58>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b2409af2052e8ddd9327582a22d15bb6/url
2023-01-21 00:39:00,721 WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x152c40cc0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b2409af2052e8ddd9327582a22d15bb6/url
2023-01-21 00:39:00,771 WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x152c40fd0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b2409af2052e8ddd9327582a22d15bb6/window
2023-01-21 00:39:00,827 WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x152c543c8>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b2409af2052e8ddd9327582a22d15bb6/window
2023-01-21 00:39:00,864 WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x152c54320>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b2409af2052e8ddd9327582a22d15bb6/window
2023-01-21 00:39:02,768 WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15105cba8>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3b9fa0d13b23c1ab1f10b39ec35cc905/url
2023-01-21 00:39:02,785 WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x151075748>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3b9fa0d13b23c1ab1f10b39ec35cc905/url
2023-01-21 00:39:02,807 WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x152c54898>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3b9fa0d13b23c1ab1f10b39ec35cc905/url
2023-01-21 00:39:02,851 WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x152c54a58>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3b9fa0d13b23c1ab1f10b39ec35cc905/window
2023-01-21 00:39:02,870 WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x152c54e48>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3b9fa0d13b23c1ab1f10b39ec35cc905/window
2023-01-21 00:39:02,912 WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x152c54da0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3b9fa0d13b23c1ab1f10b39ec35cc905/window
2023-02-25 16:56:23,884 WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15e518a58>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/a21090e22b6cb514346cfd7d7d6a658f/window
2023-02-25 16:56:23,910 WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15e51e550>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2b23df777debd1c28ac3af3a277b8a46/window
2023-02-25 16:56:23,920 WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15e505f60>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/a21090e22b6cb514346cfd7d7d6a658f/window
2023-02-25 16:56:23,926 WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15e4968d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/a7f157786aac379bfc5f4ebebfeea596/window
2023-02-25 16:56:23,928 WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15e496e48>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/c7b7e138c71099e67e2086a13ccb7ec4/window
2023-02-25 16:56:23,930 WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15e505240>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2b23df777debd1c28ac3af3a277b8a46/window
2023-02-25 16:56:23,940 WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15e7a9748>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/c7b7e138c71099e67e2086a13ccb7ec4/window
2023-02-25 16:56:23,941 WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15e7a9588>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/a7f157786aac379bfc5f4ebebfeea596/window
2023-02-25 16:56:23,942 WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15e7a9d30>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2b23df777debd1c28ac3af3a277b8a46/window
2023-02-25 16:56:23,943 WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15e505898>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/122d8de353f4519d291d54d4101830cc/window
2023-02-25 16:56:23,944 WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15e7a9828>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/a21090e22b6cb514346cfd7d7d6a658f/window
2023-02-25 16:56:23,945 WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15e7a9390>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/c7b7e138c71099e67e2086a13ccb7ec4/window
2023-02-25 16:56:23,951 WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15e48def0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/a7f157786aac379bfc5f4ebebfeea596/window
2023-02-25 16:56:23,956 WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15e70a7f0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/122d8de353f4519d291d54d4101830cc/window
2023-02-25 16:56:23,961 WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15e724978>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/122d8de353f4519d291d54d4101830cc/window
2023-02-25 17:02:10,353 WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1531e5630>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/7ce4af880aa7b56c411e886165356839/window
2023-02-25 17:02:10,359 WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1531d4ef0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/32ca4d0f69bae2ad2144f19d0c0e442a/window
2023-02-25 17:02:10,364 WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x153324a20>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/6f91a9e700fe8219dcc5aaad5d852f76/window
2023-02-25 17:02:10,366 WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1533249b0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3c573e199e1ff3e36753107070fe06cc/window
2023-02-25 17:02:10,368 WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1533df9e8>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/7ce4af880aa7b56c411e886165356839/window
2023-02-25 17:02:10,368 WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1533dfa58>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/32ca4d0f69bae2ad2144f19d0c0e442a/window
2023-02-25 17:02:10,373 WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x153389e48>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/7ce4af880aa7b56c411e886165356839/window
2023-02-25 17:02:10,374 WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1533df5c0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/6f91a9e700fe8219dcc5aaad5d852f76/window
2023-02-25 17:02:10,375 WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x153389198>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3c573e199e1ff3e36753107070fe06cc/window
2023-02-25 17:02:10,376 WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x153389c18>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/32ca4d0f69bae2ad2144f19d0c0e442a/window
2023-02-25 17:02:10,381 WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1533cbe80>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/6f91a9e700fe8219dcc5aaad5d852f76/window
2023-02-25 17:02:10,382 WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1533cb278>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3c573e199e1ff3e36753107070fe06cc/window
2023-02-25 17:02:10,886 WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x153185048>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/09d8217a871574f95d4fd4fb26d235ef/element
2023-02-25 17:02:10,906 WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1533df710>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/09d8217a871574f95d4fd4fb26d235ef/element
2023-02-25 17:02:10,929 WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x154cbb8d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/09d8217a871574f95d4fd4fb26d235ef/element
2023-02-25 17:02:10,956 WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1533fc9b0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/09d8217a871574f95d4fd4fb26d235ef/window
2023-02-25 17:02:10,961 WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x154cea3c8>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/09d8217a871574f95d4fd4fb26d235ef/window
2023-02-25 17:02:10,964 WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x154cea630>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/09d8217a871574f95d4fd4fb26d235ef/window
2023-02-25 22:22:12,361 WARNING:Retrying (Retry(total=9, connect=5, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response'))': /sitedataapi/CryptogramAPI.asmx/GetData?data=iQj8Ka97S%2Bs%3D
2023-02-25 22:22:18,372 WARNING:Retrying (Retry(total=8, connect=5, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', ConnectionResetError(54, 'Connection reset by peer'))': /sitedataapi/CryptogramAPI.asmx/GetData?data=iQj8Ka97S%2Bs%3D
2023-02-25 22:22:25,382 WARNING:Retrying (Retry(total=7, connect=5, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', ConnectionResetError(54, 'Connection reset by peer'))': /sitedataapi/CryptogramAPI.asmx/GetData?data=iQj8Ka97S%2Bs%3D
2023-02-25 22:22:34,392 WARNING:Retrying (Retry(total=6, connect=5, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', ConnectionResetError(54, 'Connection reset by peer'))': /sitedataapi/CryptogramAPI.asmx/GetData?data=iQj8Ka97S%2Bs%3D
2023-02-25 22:22:47,410 WARNING:Retrying (Retry(total=5, connect=5, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', ConnectionResetError(54, 'Connection reset by peer'))': /sitedataapi/CryptogramAPI.asmx/GetData?data=iQj8Ka97S%2Bs%3D
2023-02-25 22:23:08,424 WARNING:Retrying (Retry(total=4, connect=5, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', ConnectionResetError(54, 'Connection reset by peer'))': /sitedataapi/CryptogramAPI.asmx/GetData?data=iQj8Ka97S%2Bs%3D
2023-02-25 22:23:45,443 WARNING:Retrying (Retry(total=3, connect=5, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', ConnectionResetError(54, 'Connection reset by peer'))': /sitedataapi/CryptogramAPI.asmx/GetData?data=iQj8Ka97S%2Bs%3D
2023-02-25 22:24:54,448 WARNING:Retrying (Retry(total=2, connect=5, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', ConnectionResetError(54, 'Connection reset by peer'))': /sitedataapi/CryptogramAPI.asmx/GetData?data=iQj8Ka97S%2Bs%3D
2023-02-25 22:26:59,458 WARNING:Retrying (Retry(total=1, connect=5, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', ConnectionResetError(54, 'Connection reset by peer'))': /sitedataapi/CryptogramAPI.asmx/GetData?data=iQj8Ka97S%2Bs%3D
2023-02-25 22:29:04,470 WARNING:Retrying (Retry(total=0, connect=5, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', ConnectionResetError(54, 'Connection reset by peer'))': /sitedataapi/CryptogramAPI.asmx/GetData?data=iQj8Ka97S%2Bs%3D
2023-02-26 17:58:58,591 WARNING:Retrying (Retry(total=9, connect=4, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x15dd82b38>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /sitedataapi/CryptogramAPI.asmx/GetData?data=FjyRZNBlvrE%3D
2023-02-26 17:58:59,693 WARNING:Retrying (Retry(total=8, connect=3, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x15f74cac8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /sitedataapi/CryptogramAPI.asmx/GetData?data=FjyRZNBlvrE%3D
2023-02-26 17:59:01,695 WARNING:Retrying (Retry(total=9, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response'))': /djapi/fund/013994
2023-02-26 17:59:01,704 WARNING:Retrying (Retry(total=7, connect=2, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x15f749898>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /sitedataapi/CryptogramAPI.asmx/GetData?data=FjyRZNBlvrE%3D
2023-02-26 17:59:02,780 WARNING:Retrying (Retry(total=8, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /djapi/fund/013994
2023-02-26 17:59:05,029 WARNING:Retrying (Retry(total=7, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /djapi/fund/013994
2023-02-26 17:59:05,752 WARNING:Retrying (Retry(total=6, connect=1, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x15f7495f8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /sitedataapi/CryptogramAPI.asmx/GetData?data=FjyRZNBlvrE%3D
2023-02-26 17:59:09,064 WARNING:Retrying (Retry(total=6, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', ConnectionResetError(54, 'Connection reset by peer'))': /djapi/fund/013994
2023-02-26 18:00:00,090 WARNING:Retrying (Retry(total=5, connect=0, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x15f777160>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /sitedataapi/CryptogramAPI.asmx/GetData?data=FjyRZNBlvrE%3D
2023-02-26 18:00:00,084 WARNING:Retrying (Retry(total=5, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /djapi/fund/013994
2023-02-26 18:00:35,323 WARNING:Retrying (Retry(total=4, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /djapi/fund/013994
2023-02-26 18:01:08,649 WARNING:Retrying (Retry(total=3, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /djapi/fund/013994
2023-02-26 18:02:17,656 WARNING:Retrying (Retry(total=2, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', ConnectionResetError(54, 'Connection reset by peer'))': /djapi/fund/013994
2023-02-26 18:03:07,716 WARNING:Retrying (Retry(total=9, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response'))': /djapi/fund/014617
2023-02-26 18:09:24,098 WARNING:Retrying (Retry(total=1, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /djapi/fund/013994
2023-02-26 18:09:24,488 WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15dc20d68>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2eacc25b6c10034d1590c278f5f512e8/cookie
2023-02-26 18:09:24,489 WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1528a5fd0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2eacc25b6c10034d1590c278f5f512e8/cookie
2023-02-26 18:09:24,491 WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1584e9898>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2eacc25b6c10034d1590c278f5f512e8/cookie
2023-02-26 18:09:24,493 WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x158700748>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2eacc25b6c10034d1590c278f5f512e8/window
2023-02-26 18:09:24,494 WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x158700ac8>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2eacc25b6c10034d1590c278f5f512e8/window
2023-02-26 18:09:24,495 WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x158700128>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2eacc25b6c10034d1590c278f5f512e8/window
2023-02-26 18:29:59,388 WARNING:Retrying (Retry(total=9, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response'))': /webinterface/Bamboo.ashx?command=singlefundAnalyse
2023-02-26 18:30:05,414 WARNING:Retrying (Retry(total=8, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', ConnectionResetError(54, 'Connection reset by peer'))': /webinterface/Bamboo.ashx?command=singlefundAnalyse
2023-02-26 18:30:12,422 WARNING:Retrying (Retry(total=7, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', ConnectionResetError(54, 'Connection reset by peer'))': /webinterface/Bamboo.ashx?command=singlefundAnalyse
2023-02-26 18:30:21,426 WARNING:Retrying (Retry(total=6, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', ConnectionResetError(54, 'Connection reset by peer'))': /webinterface/Bamboo.ashx?command=singlefundAnalyse
2023-02-26 18:30:34,437 WARNING:Retrying (Retry(total=5, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', ConnectionResetError(54, 'Connection reset by peer'))': /webinterface/Bamboo.ashx?command=singlefundAnalyse
2023-02-26 18:30:55,442 WARNING:Retrying (Retry(total=4, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', ConnectionResetError(54, 'Connection reset by peer'))': /webinterface/Bamboo.ashx?command=singlefundAnalyse
2023-02-26 18:31:32,447 WARNING:Retrying (Retry(total=3, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', ConnectionResetError(54, 'Connection reset by peer'))': /webinterface/Bamboo.ashx?command=singlefundAnalyse
2023-02-26 18:32:41,451 WARNING:Retrying (Retry(total=2, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', ConnectionResetError(54, 'Connection reset by peer'))': /webinterface/Bamboo.ashx?command=singlefundAnalyse
2023-02-26 18:34:46,455 WARNING:Retrying (Retry(total=1, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', ConnectionResetError(54, 'Connection reset by peer'))': /webinterface/Bamboo.ashx?command=singlefundAnalyse
2023-02-26 18:36:35,269 WARNING:Retrying (Retry(total=9, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response'))': /webinterface/Bamboo.ashx?command=singlefundAnalyse
2023-02-26 18:37:22,009 WARNING:Retrying (Retry(total=9, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response'))': /webinterface/Bamboo.ashx?command=singlefundAnalyse
2023-02-26 18:42:13,921 WARNING:Retrying (Retry(total=8, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response'))': /webinterface/Bamboo.ashx?command=singlefundAnalyse
2023-02-26 18:43:49,569 WARNING:Retrying (Retry(total=9, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response'))': /webinterface/Bamboo.ashx?command=singlefundAnalyse
2023-02-26 18:56:23,752 WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x150f1b0b8>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e8b67d0f9c40eb4d1f180ee88f6e3ea6/window
2023-04-30 22:52:40,996 WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x153845a58>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/77e8056a1c13e5b584f771b5e1b25191/element
2023-04-30 22:52:41,004 WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x153f25a90>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/77e8056a1c13e5b584f771b5e1b25191/element
2023-04-30 22:52:41,025 WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x153845cf8>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/77e8056a1c13e5b584f771b5e1b25191/element
2023-05-01 20:06:30,583 WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x159af82b0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/eeb702c624dbeac1cc1b463f87695e58/window
2023-05-01 20:06:30,588 WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x154144080>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/ff1928b7ae463188926d031e6a1c1346/window
2023-05-01 20:06:30,666 WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15412b940>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/eeb702c624dbeac1cc1b463f87695e58/window
2023-05-01 20:06:30,685 WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x154144908>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/ff1928b7ae463188926d031e6a1c1346/window
2023-05-01 20:06:30,689 WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x154144780>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/eeb702c624dbeac1cc1b463f87695e58/window
2023-05-01 20:06:30,692 WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x154144d30>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/ff1928b7ae463188926d031e6a1c1346/window
2023-05-01 20:06:30,817 WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x159808208>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/5ace09293a982acc49a02d4447648c3d/window
2023-05-01 20:06:30,824 WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x159ad4358>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/5ace09293a982acc49a02d4447648c3d/window
2023-05-01 20:56:38,282 WARNING:Retrying (Retry(total=9, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /djapi/fund/007490
2023-05-01 22:57:03,368 WARNING:Retrying (Retry(total=9, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', ConnectionResetError(54, 'Connection reset by peer'))': /djapi/fund/012443
2023-05-01 22:57:09,377 WARNING:Retrying (Retry(total=8, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', ConnectionResetError(54, 'Connection reset by peer'))': /djapi/fund/012443
2023-05-01 22:57:16,383 WARNING:Retrying (Retry(total=7, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', ConnectionResetError(54, 'Connection reset by peer'))': /djapi/fund/012443
2023-05-01 22:57:22,467 WARNING:Retrying (Retry(total=9, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', ConnectionResetError(54, 'Connection reset by peer'))': /djapi/fund/530015
2023-05-01 22:57:25,393 WARNING:Retrying (Retry(total=6, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', ConnectionResetError(54, 'Connection reset by peer'))': /djapi/fund/012443
2023-05-01 22:57:28,469 WARNING:Retrying (Retry(total=8, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', ConnectionResetError(54, 'Connection reset by peer'))': /djapi/fund/530015
2023-05-01 23:03:55,619 WARNING:Retrying (Retry(total=9, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', ConnectionResetError(54, 'Connection reset by peer'))': /djapi/fund/012594
2023-05-01 23:03:55,887 WARNING:Retrying (Retry(total=9, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', ConnectionResetError(54, 'Connection reset by peer'))': /djapi/fund/011283
2023-05-01 23:04:01,621 WARNING:Retrying (Retry(total=8, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', ConnectionResetError(54, 'Connection reset by peer'))': /djapi/fund/012594
2023-05-02 06:05:28,593 WARNING:Retrying (Retry(total=9, connect=3, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response'))': /djapi/fund/007154
2023-05-02 06:05:55,806 WARNING:Retrying (Retry(total=9, connect=5, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response'))': /sitedataapi/CryptogramAPI.asmx/GetData?data=HoFayyAx0fc%3D
2023-05-02 06:08:56,789 WARNING:Retrying (Retry(total=9, connect=5, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response'))': /sitedataapi/CryptogramAPI.asmx/GetData?data=jW88srsRCBc%3D
